Deprecate old astartectl cluster *-operator commands
astarte-platform/astartectl pull request #117
Opened 2020-11-16 15:02 UTC by rbino

Print instructions to do the same thing using Helm

Fix #115

Signed-off-by: Riccardo Binetti <riccardo.binetti@ispirata.com>

2020-11-17 08:29 UTC, matt-mazzucato approved these changes

2020-11-20 11:53 UTC, bettio commented on cmd/cluster/install_operator.go
> +Since Astarte 1.0, operator installation through astartectl has been removed. You can install astarte-operator using Helm (https://helm.sh/) with these commands:
let's add a TODO about linking documentation as soon as possible.

2020-11-20 11:54 UTC, bettio requested changes
let's link the documentation as soon as possible instead of hardcoding shell commands.

2020-11-24 12:28 UTC, bettio approved these changes

2020-11-24 12:28 UTC, merged