Device: replace metadata with attributes
astarte-platform/astartectl pull request #129
Opened 2021-03-22 17:31 UTC by matt-mazzucato

To keep coherency in terminology replace device metadata with device
attributes.

2021-03-24 16:23 UTC, rbino requested changes

2021-03-24 16:23 UTC, rbino commented on cmd/appengine/device_metadata.go
>  	metaKeyAndValue := args[1]
`meta` stands for `metadata`, let's keep the naming consistent

2021-03-26 12:05 UTC, rbino approved these changes

2021-03-26 12:22 UTC, bettio approved these changes

2021-03-26 12:22 UTC, merged