realm/interfaces/sync: Allow non-interactive mode
astarte-platform/astartectl pull request #145
Opened 2022-02-01 10:44 UTC by drf

2022-02-01 11:29 UTC, Annopaolo approved these changes

2022-02-02 13:02 UTC, bettio approved these changes

2022-02-02 13:03 UTC, bettio requested changes
This is a relevant feature, can we add it to the changelog?

2022-02-09 10:27 UTC, bettio approved these changes

2022-02-09 10:27 UTC, merged