Add exceptions for aggregate payload
astarte-platform/astartectl pull request #248
Opened 2024-05-07 13:12 UTC by eddbbt

Add exceptions for aggregate payloads of type longintegerarray and integerarray when sending data to astarte. It is now correctly parsed before sending instead of being treated like interface arrays

2024-06-25 09:25 UTC, matt-mazzucato requested changes
I think that an entry in the Changelog is needed for this change.
In addition, what about rebasing the PR on master?
cc @Annopaolo

2024-06-25 09:25 UTC, matt-mazzucato commented on cmd/appengine/device.go
> +
Extra line here.

2024-06-25 16:02 UTC, Annopaolo commented
> I think that an entry in the Changelog is needed for this change. In addition, what about rebasing the PR on master? cc @Annopaolo

Yes, a `CHANGELOG.md` line is needed.
However, I would suggest keeping this on release-23.5 as it's still the latest supported release and contains a number of fixes for the interaction with Astarte APIs

2024-06-26 08:48 UTC, Annopaolo requested changes

2024-06-26 08:48 UTC, Annopaolo commented on CHANGELOG.md
> +- `appengine send-data`: fix the decoding of longinteger and longintegerarray
`send-data` has been deprecated, use  `publish-datastream` in the changelog

2024-06-26 08:48 UTC, Annopaolo commented on CHANGELOG.md
> +  before sending to astarte. Those are no lomnger treated like interface arrays
Typo (lomger --> longer), but I'd suggest to remove the "Those..." line, as it does not give much information to the user (it's more about the internals of astartectl)

2024-06-26 09:21 UTC, Annopaolo requested changes

2024-06-26 09:21 UTC, Annopaolo commented on CHANGELOG.md
> +- `appengine {publish-datastream set-property}`: fix the decoding of longinteger
The change seems to be only inside `devicesPublishDataStreamF`, could you check if it is in `set-property` too?

2024-06-26 09:21 UTC, Annopaolo commented on cmd/appengine/device.go
> +				}
See my previous comment: these lines are inside `devicesPublishDataStreamF` but not in `devicesSetPropertyF`

2024-06-26 09:24 UTC, Annopaolo commented on CHANGELOG.md
> +- `appengine {publish-datastream set-property}`: fix the decoding of longinteger
Edit: it makes sense, as aggregated properties do not exist

2024-06-26 10:54 UTC, Annopaolo approved these changes

2024-06-26 10:54 UTC, matt-mazzucato approved these changes

2024-06-26 10:54 UTC, merged